[TRAVIS] find most recent Python on OSX
Avoid a problem when multiple python 3 versions are installed on OSX.

Closes #220

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -76,8 +76,6 @@ before_install:
       brew cask uninstall oclint
       brew install ccache
       export PATH="/usr/local/opt/ccache/libexec:$PATH"
-      # use Python3 on Mac
-      brew upgrade python
       # Install ROOT, unless disabled
       case "$EXTRA_BUILD_FLAGS" in
           *DISABLE_CERN_ROOT=1*)
@@ -86,12 +84,22 @@ before_install:
               brew install root;;
       esac
       brew install swig
+      # use Python3 on Mac
+      brew upgrade python || true # don't fail if upgrading doesn't do anything
       # find exact location of Python executable to pass to CMake
-      PY_INST=`echo /usr/local/Cellar/python/3.*/Frameworks/Python.framework/Versions/3.*`
-      PY_EXE=$PY_INST/bin/python3
-      PY_LIB=$PY_INST/Python
-      PY_INC=$PY_INST/Headers
-      # This is not necessary if we give the actual path for the executable
+      # we attempt to find the last one if there are multiple Python 3 versions installed
+      PYMVER=3
+      PY_INST=$(ls -d1 /usr/local/Cellar/python/$PYMVER.*/Frameworks/Python.framework/Versions/$PYMVER.*|tail -n 1)
+      PYMVER=$(basename ${PY_INST})
+      PY_EXE=$PY_INST/bin/python$PYMVER
+      if [ ! -x "$PY_EXE" ]; then
+        echo "Something wrong with finding Python executable for OSX"
+        echo "PY_EXE = $PY_EXE"
+        travis_terminate 1
+      fi
+      # Next lines are not necessary if we give the actual path for the executable to cmake
+      #PY_LIB=$PY_INST/Python
+      #PY_INC=$PY_INST/Headers
       # BUILD_FLAGS="$BUILD_FLAGS -DPYTHON_LIBRARY=$PY_LIB -DPYTHON_INCLUDE_DIR=$PY_INC"
       ${PY_EXE} -m pip install -U pip
       ${PY_EXE} -m pip install pytest numpy
